_BACKGROUND_NAMES = ['ground', 'goal_site', '', 'arena']

_GOOGLE_ROBOT_NAMES = [
    'link_base',
    'link_base_inertial',
    'link_wheel_left',
    'link_wheel_right',
    'link_rear_wheel_left',
    'link_rear_wheel_right',
    'link_torso',
    'link_shoulder',
    'link_bicep',
    'link_elbow',
    'link_forearm',
    'link_wrist',
    'link_gripper',
    'link_gripper_tcp',
    'link_finger_right',
    'link_finger_tip_right',
    'link_finger_nail_right',
    'link_finger_left',
    'link_finger_tip_left',
    'link_finger_nail_left',
    'link_head_pan',
    'link_head_tilt',
    'link_camera',
    'link_base_imu_mount',
    'imu.base',
    'link_neck_imu_mount',
    'imu.neck',
    'time_of_flight.right_1',
    'time_of_flight.right_2',
    'time_of_flight.right_back_1',
    'time_of_flight.right_back_2',
    'time_of_flight.left_1',
    'time_of_flight.left_2',
    'time_of_flight.left_back_1',
    'time_of_flight.left_back_2',
    'cliff.rear_right',
    'cliff.rear_left',
]

_WIDOWX_ROBOT_NAMES = [
    'base_link',
    'shoulder_link',
    'upper_arm_link',
    'upper_forearm_link',
    'lower_forearm_link',
    'wrist_link',
    'gripper_link',
    'ee_arm_link',
    'gripper_prop_link',
    'gripper_bar_link',
    'fingers_link',
    'left_finger_link',
    'right_finger_link',
    'ee_gripper_link',
]

_PANDA_ROBOT_NAMES = [
    'panda_link0',
    'panda_link1',
    'panda_link2',
    'panda_link3',
    'panda_link4',
    'panda_link5',
    'panda_link6',
    'panda_link7',
    'panda_link8',
    'panda_hand',
    'panda_hand_tcp',
    'panda_leftfinger',
    'panda_rightfinger',
    'panda_leftfinger_pad',
    'panda_rightfinger_pad',
]

_ROBOT_NAMES = _GOOGLE_ROBOT_NAMES + _WIDOWX_ROBOT_NAMES + _PANDA_ROBOT_NAMES